config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :admin do
    resources :categories, except: :destroy do
      resources :varieties, except: [:show]
    end
    resources :users, only: [:index, :update]
  end

  namespace :api do
    resources :categories, only:[] do
      resources :varieties, only: [:index]
    end
  end

  resources :gardens, except: [:new] do
    resources :shapes, only: [:create, :update, :destroy]
  end
  resources :password_resets, except: [:index, :show, :destroy]
  resource :user, except: [:destroy]
  resource :user_session, only: [:new, :create, :destroy]

end

app/models/variety.rb
class Variety < ActiveRecord::Base
  mount_uploader :side_image, PlantImageUploader
  mount_uploader :top_image, PlantImageUploader

  belongs_to :category
  validates_presence_of :category, :name
  validates_uniqueness_of :name, message: "already exists."

  def full_title
    "#{name} (#{description})"
  end
end

app/controllers/admin/varieties_controller.rb
class Admin::VarietiesController < AdminController
  before_action :load_category

  def new
    @variety = Variety.new
  end

  def create
    @variety = @category.varieties.build(variety_params)
    if @variety.save
      redirect_to admin_category_path(@category), notice: "The #{@variety.name} variety has been created."
    else
      flash.now[:alert] = "Variety could not be created."
      render :new
    end
  end

  def edit
    @variety = Variety.find(params[:id])
  end

  def update
    @variety = Variety.find(params[:id])
    if @variety.update(variety_params)
      redirect_to edit_admin_category_variety_path(@variety.category, @variety), notice: "The #{@variety.name} variety has been updated."
    else
      flash.now[:alert] = "Variety could not be updated."
      render :new
    end
  end

  def destroy
    Variety.find(params[:id]).destroy
    redirect_to admin_category_path(@category), notice: "Variety has been deleted."
  end

  protected

  def variety_params
    params.require(:variety).permit(:name, :description, :side_image, :top_image)
  end

  def load_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/api/varieties_controller.rb
class Api::VarietiesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    respond_to do |format|
      if @category.varieties.count < 1
        format.html { render html: "<p>No varieties exist</p>" }
      else
        format.html { render partial: "varieties" }
      end
    end
  end
end

app/controllers/varieties_controller.rb
class VarietiesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    respond_to do |format|
      format.json { render json: @category.varieties }
    end
  end
end

app/views/varieties/edit.html.haml
%h1= "Editing " + @variety.full_title

= simple_form_for @variety, url: category_variety_path(@category, @variety) do |f|
  = f.input :name
  = f.input :description
  = f.input :top_image, label: "Top Image"
  - if @variety.top_image.present?
    = image_tag @variety.top_image.url(:thumb), class: "top_image"
  = f.input :side_image, label: "Side Image"
  - if @variety.side_image.present?
    = image_tag @variety.side_image.url(:thumb), class: "side_image"
  = f.submit "Save Changes"

= button_to "Delete Variety", category_variety_path(@category, @variety), method: :delete, data: { confirm: "Are you sure?"}, class: "small button alert"

app/views/varieties/new.html.haml
= simple_form_for @variety, url: category_varieties_path do |f|
  = f.input :name
  = f.input :description
  = f.input :top_image, label: "Top Image"
  = f.input :side_image, label: "Side Image"
  = f.submit "Create New Variety"