config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :admin do
    resources :categories, except: :destroy do
      resources :varieties, except: [:show]
    end
    resources :users, only: [:index, :update]
  end

  namespace :api do
    resources :categories, only:[] do
      resources :varieties, only: [:index]
    end
  end

  resources :gardens, except: [:new] do
    resources :shapes, only: [:create, :update, :destroy]
  end
  resources :password_resets, except: [:index, :show, :destroy]
  resource :user, except: [:destroy]
  resource :user_session, only: [:new, :create, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  mount_uploader :side_image, CategoryImageUploader

  validates_presence_of :name
  has_many :varieties
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "The #{@category.name} category has been created."
    else
      flash.now[:alert] = "Category could not be created."
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: "The #{@category.name} category has been updated."
    else
      flash.now[:alert] = "Your changes could not be saved."
      render :edit
    end
  end

  protected

  def category_params
    params.require(:category).permit(:name, :edible, :side_image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "The #{@category.name} category has been created."
    else
      flash.now[:alert] = "Category could not be created."
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: "The #{@category.name} category has been updated."
    else
      flash.now[:alert] = "Your changes could not be saved."
      render :edit
    end
  end

  protected

  def category_params
    params.require(:category).permit(:name, :edible)
  end
end

app/views/admin/categories/_category.html.haml
%li
  = link_to category.name, admin_category_path(category)
  = image_tag category.side_image.url(:thumb), class: "side_image"

app/views/admin/categories/edit.html.haml
%h1= "Editing " + @category.name + " Category"

= simple_form_for [:admin, @category] do |f|
  = f.input :name
  = f.input :edible
  = f.submit "Update Plant Category"

app/views/admin/categories/index.html.haml
%h1 Plant Categories
%ul#categories= render @categories
= link_to "Add Category", new_admin_category_path, class: "button"

app/views/admin/categories/new.html.haml
= simple_form_for [:admin, @category] do |f|
  = f.input :name
  = f.input :edible
  = f.input :side_image, label: "Side Image"
  = f.submit "Create Category"

app/views/admin/categories/show.html.haml
%h1
  = @category.name
  = image_tag @category.side_image.url(:thumb), class: "side_image"
= link_to "Edit Plant Category", edit_admin_category_path(@category), class: "button small secondary"
%hr

%h2 #{@category.name} Varieties:
%ul#varieties
  - @category.varieties.each do |variety|
    %li
      = image_tag variety.side_image.url(:thumb), class: "side_image"
      = image_tag variety.top_image.url(:thumb), class: "top_image"
      = link_to variety.full_title, edit_admin_category_variety_path(@category, variety)

= link_to "Add New #{@category.name} Variety", new_admin_category_variety_path(@category), class: "button small"