config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :admin do
    resources :categories, except: :destroy do
      resources :varieties, except: [:show]
    end
    resources :users, only: [:index, :update]
  end

  namespace :api do
    resources :categories, only:[] do
      resources :varieties, only: [:index]
    end
  end

  resources :gardens, except: [:new] do
    resources :shapes, only: [:create, :update, :destroy]
  end
  resources :password_resets, except: [:index, :show, :destroy]
  resource :user, except: [:destroy]
  resource :user_session, only: [:new, :create, :destroy]

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "GreenThumb!"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    <script type="text/javascript" src="//use.typekit.net/ayn0ftv.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  %body
    %nav#main
      %ul
        - if logged_in?
          - unless request.path == root_path
            %li= link_to "< Back to Dashboard", root_path
          %li= link_to "Profile", edit_user_path
          %li= link_to "Sign Out", user_session_path, method: :delete
        - else
          %li= link_to "Sign In", new_user_session_path
          %li= link_to "Sign Up", new_user_path
      = link_to root_path, id: "logo" do
        %h2.title
          = image_tag "POGO_10.090_OCA.svg", class: "logo"
          GreenThumb
    %main
      - if notice.present?
        .alert-box.success{ "data-alert" => "" }
          = notice
          %a.close{ href: "#" } &times;
      - if alert.present?
        .alert-box.alert{ "data-alert" => "" }
          = alert
          %a.close{ href: "#" } &times;
      = yield
    %footer
      - if logged_in? and current_user.admin?
        = link_to "Manage Plant Categories", admin_categories_path
        = link_to "Manage Users", admin_users_path

    = javascript_include_tag "application"
    = javascript_tag '$.fx.off = true;' if Rails.env.test?